version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test2107Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.test2107.integrations:ref1_Call
  packages:
  - name: Test2107Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.test2107.referencedata:ref1
  packages:
  - name: Test2107Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
